PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX ship: <http://example.org/ship#>
PREFIX ex: <http://example.org/individuals#>

SELECT DISTINCT ?sensor
WHERE {
  ?sensor a ship:EngineSensor ;
          sosa:observes ex:RotationSpeed .

}

