PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?sensor ?sensorType
WHERE {
  ?sensor a ?sensorType .
  ?sensorType rdfs:subClassOf sosa:Sensor .
}
