PREFIX ship: <http://example.org/ship#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX ex: <http://example.org/individuals#>

SELECT DISTINCT ?lowerBound ?upperBound
WHERE {
  ex:FuelTank01Sensor ship:hasSensorProperty ?alarmRange .
  
  ?alarmRange a ship:AlarmThresholdRange ;
              qudt:lowerBound ?lowerBound ;
              qudt:upperBound ?upperBound .
}

