# C02.3g - Which physical conditions are detected by sensors, and what do they indicate?

PREFIX ssn: <http://www.w3.org/ns/ssn/>

SELECT ?sensor ?stimulus ?observableProperty
WHERE {
  ?sensor ssn:detects ?stimulus .
          
  ?stimulus ssn:isProxyFor ?observableProperty .
}