# C01.3u - What physical property is measured by fuel tank sensors?

PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX ship: <http://example.org/ship#>
PREFIX ex: <http://example.org/individuals#>
PREFIX ssn: <http://www.w3.org/ns/ssn/>

SELECT DISTINCT ?sensor ?observedProperty
WHERE {
  ?sensor a ship:GeneralSensor ;
          sosa:madeObservation ?observation .
		  
  ?observation sosa:hasFeatureOfInterest ex:FuelLevel ;
          sosa:observedProperty ?observedProperty .
}

